name: CMake Build for WebView2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release  # 或 Debug，根据需要设置

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install WebView2 Runtime
      run: |
        # 安装 WebView2 运行时
        Invoke-WebRequest -Uri https://aka.ms/webview2/installer -OutFile webview2_installer.exe
        Start-Process -Wait -FilePath .\webview2_installer.exe -ArgumentList "/silent", "/install"
    
    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -G "Visual Studio 16 2019"

    - name: Build the project
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
