name: CMake + vcpkg Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up vcpkg
      uses: microsoft/vcpkg-action@v2
      with:
        vcpkgDirectory: ${{ env.VCPKG_ROOT }}

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[16.9]'

    - name: Install dependencies with vcpkg
      run: |
        ./vcpkg install <your-package-list> # List your dependencies here
        ./vcpkg integrate install

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 16 2019" ..
      
    - name: Build project
      run: |
        cd build
        msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} ${env.SOLUTION_FILE_PATH}
