name: CMake Build with vcpkg and MSVC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # 配置构建类型 (Release 或 Debug)
  BUILD_TYPE: Release  # 可以根据需求改为 Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest  # 使用预配置的 Windows 环境，默认配备 MSVC 和相关工具

    steps:
    - uses: actions/checkout@v4  # 检出代码

    - name: Set up vcpkg
      run: |
        # 克隆 vcpkg 仓库
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        # 安装 vcpkg 并初始化
        ./bootstrap-vcpkg.bat
        # 安装您需要的第三方库（例如：webview2, simpleini, fmt）
        ./vcpkg install webview2 simpleini fmt

    - name: Set up Visual Studio with C++ Build Tools
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 2019  # 使用 Visual Studio 2019 或者其他版本
        msbuild-architecture: x64  # 使用 x64 架构
        include-workload: "Desktop development with C++"  # 确保安装 C++ 开发工具集

    - name: Configure CMake with vcpkg toolchain
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build the project with MSVC
      run: |
        cmake --build ${{ github.workspace }}/build --config ${env.BUILD_TYPE}

    - name: Run tests (optional)
      run: |
        ctest --build-directory ${{ github.workspace }}/build --config ${env.BUILD_TYPE}
